/*BORRADO DE TABLAS*/
DROP TABLE PERSONA;
DROP TABLE CONCESIONARIO;
DROP TABLE COMBUSTIBLE;
DROP TABLE RUEDA;
DROP TABLE COCHE;

/*Primera tabla*/
CREATE TABLE COCHE(
    NUM_BASTIDOR VARCHAR2(20),
    MARCA_COCHE VARCHAR2(20),
    TIPO_COCHE VARCHAR2(20),
    COLOR VARCHAR2(10),
    MATRICULA VARCHAR2(7) UNIQUE, /*La matricula de cualquier coche es única por lo que ponemos UNIQUE, ademas de identificarla con una FOREING KEY(de la tabla)*/
    CONSTRAINT COC_NUM_PK PRIMARY KEY (NUM_BASTIDOR) /*La clave primaria que identifica a un coche es el NUM_BASTIDOR, y se identifica como CONSTRAINT(de la tabla)*/
);
/*Segunda tabla*/
CREATE TABLE RUEDA(
    IDENTIFICADOR NUMBER(20),
    MEDIDA VARCHAR2(20),
    MARCA_RUEDA VARCHAR2(20),    
    CONSTRAINT RUE_MED_PK PRIMARY KEY (IDENTIFICADOR), /*La clave primaria que identifica a una rueda es la MEDIDA, y se identifica como CONSTRAINT(de la tabla)*/
);

/*Tercera tabla*/
CREATE TABLE COMBUSTIBLE(
    TIPO_COM VARCHAR2(8),
    MARCA_COM VARCHAR2(10),
    CLASE_COM NUMBER(2),    
	CONSTRAINT COM_PRI_PK PRIMARY KEY(TIPO_COM,MARCA_COM,CLASE_COM)/*La clave primaria es compuesta por lo que se crea una CONSTRAINT con las claves*/
);

/*Cuarta tabla*/
CREATE TABLE CONCESIONARIO(    
    NIF VARCHAR2(10) PRIMARY KEY,/*Creamos la clave primaria a nivel de a columna*/
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    COD_POSTAL NUMBER(5) 
);

/*Quinta tabla*/
CREATE TABLE PERSONA(
    DNI CHAR(9) PRIMARY KEY,/*Creamos la clave primaria a nivel de columna*/
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,/*El nombre y los apellidos no pueden ser nulos por lo que ponemos NOT NULL*/
    EDAD NUMBER(3) CHECK (EDAD > 18 AND EDAD <= 100),/*Creamos una CONSTRAINT CHECK para limitar la edad con la que puedes comprar el coche, pero la creamos en nivel de columna*/
    DINERO NUMBER(6,2) DEFAULT 500,/*Se usa DEFAULT para que le asigne un valor mínimo por defecto para que por lo menos el banco te pueda financiar*/
    PAISORIGEN VARCHAR2(8),
    CONSTRAINT PER_DIN_CK CHECK (DINERO BETWEEN 500 AND 10000)/*Este CONSTRAINT compara el dinero que puedes tener*/
);

--Datos
INSERT INTO COCHE VALUES ('W2E11D3CDS2B54D19', 'FORD', '5 PLAZAS', 'BLANCO', '4455BCS');
INSERT INTO COCHE VALUES ('3FD12FVF2X2F2EG3B', 'PEUGEOT', '7 PLAZAS', 'ROJO', '6235YHT');
INSERT INTO COCHE VALUES ('8B5F5D2BV1B2544FV', 'AUDI', 'MONOVOLUMEN', 'NEGRO', '7895LYV');
INSERT INTO COCHE VALUES ('2F2G99JR5F8M1H6JT', 'MERCEDES', '5 PLAZAS', 'AZUL', '2564RSD');
INSERT INTO COCHE VALUES ('9HT8YH5J11WD6CF85', 'LAMBORGHINI', '5 PLAZAS', 'BLANCO', '2542LRM');

INSERT INTO RUEDA VALUES (1245254632, '195-65-R/13', 'MICHELIN');
INSERT INTO RUEDA VALUES (5421698735, '215-65-R/13', 'PIRELLI');
INSERT INTO RUEDA VALUES (9652354178, '225-70-R/13', 'FIRESTONE');

INSERT INTO COMBUSTIBLE VALUES ('GASOIL', 'REPSOL', 95);
INSERT INTO COMBUSTIBLE VALUES ('GASOLINA', 'CEPSA', 95);
INSERT INTO COMBUSTIBLE VALUES ('GASOIL', 'CEPSA', 98);

INSERT INTO CONCESIONARIO VALUES ('U54265217', 'FORD', 'C/ROMANA, 32', 'ALCALA DE GUADAIRA', 'SEVILLA', 41200);
INSERT INTO CONCESIONARIO VALUES ('A32548652', 'PEUGEOT', 'C/ESPARTINA, 45', 'VILLALBA DEL ALCOR', 'SEVILLA', 41021);
INSERT INTO CONCESIONARIO VALUES ('F45789511', 'AUDI', 'C/GUZMAN, 10', 'SEVILLA', 'SEVILLA', 41010);
INSERT INTO CONCESIONARIO VALUES ('G25634583', 'MERCEDES', 'C/AGUILA, 1', 'VISO DEL ALCOR', 'SEVILLA', 41501);
INSERT INTO CONCESIONARIO VALUES ('Q25498756', 'LAMBORGHINI', 'C/RAMIREZ, 20', 'CORIA DEL RIO', 'SEVILLA', 41745);

INSERT INTO PERSONA VALUES ('21354658T', 'JUAN', 'PEREZ MARTIN', 25, 10200, 'HUELVA');
INSERT INTO PERSONA VALUES ('65423894Q', 'LAURA', 'GARCIA RAMIREZ', 19, 2010, 'CADIZ');
INSERT INTO PERSONA VALUES ('51241134D', 'HUGO', 'RUIZ GOMEZ', 45, 5200, 'CORDOBA');
INSERT INTO PERSONA VALUES ('36548975S', 'PEDRO', 'RODRIGUEZ LOPEZ', 54, 40201, 'ALMERIA');
INSERT INTO PERSONA VALUES ('32569856H', 'ERIKA', 'MARTINEZ JIMENEZ', 20, 1600, 'GRANADA');

COMMIT;
